[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-venv", "gcc", "libpq-dev"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[start]
cmd = "python app/main.py"
